### PR TITLE
Use Vitest as Testing Framework

### PR DESCRIPTION
**Pull request by EagleoutIce**
On my machine this lowers testing times from around 34s to 5.9s!

### CODE REVIEW

**Comment by EagleoutIce** [comment]
Please check if this works for you and checkout the new (sadly for now reduced docs): https://github.com/flowr-analysis/flowr/blob/57d94d5c9cd2316f6e611fea9fb9d24c993e3077/wiki/Linting%20and%20Testing.md

The main reason for them being reduced for now is that i right now do not have the time to check how to run this in vscode/webstorm.

**Comment by by-lars** [comment]
3.82s :rocket:

**Review by Ellpeck — APPROVED** [review]

**Review by by-lars — APPROVED** [review]

**Comment by EagleoutIce** [comment]
_This pull request is included in v2.1.6 (see [Release v2.1.6 (Include Source-File Information, Vitest, and Documentation)](https://github.com/flowr-analysis/flowr/releases/tag/v2.1.6))._

**Comment by EagleoutIce** [comment]
_This pull request is included in v2.1.6 (see [Release v2.1.6 (Include Source-File Information, Vitest, and Documentation)](https://github.com/flowr-analysis/flowr/releases/tag/v2.1.6))._

**Pull request merged**
