### PR TITLE
Type-safe R entry parsing

### LINKED ISSUE #670: Refactor `XmlBasedJson` to make it type-safe now that `convertToXmlBasedJson` ensures a very specific structure
When #659 is merged, we should refactor the `XmlBasedJson` type to be type-safe, since the new csv-based parser's `convertToXmlBasedJson` function causes it to always have a specific structure.

### PR DESCRIPTION
**Pull request by bjthehun**
Fixes #670. Use `JsonEntry` instead of `XmlBasedJson`, and remove type-unsafe accesses.

### CODE REVIEW

**Comment by bjthehun** [comment]
@EagleoutIce @Ellpeck I need someone of you to assist me with dealing with the conflict in `cli/src/repl/commands/parse.ts`, now that this file has been moved to its own repository.

**Review by bjthehun — COMMENTED** [review]
Sorry for not having worked on this pull request recently. I'm currently busy looking for a position as scientific assistant, and I hope I'll be able to resolve this issue soon.

**Comment by EagleoutIce** [comment]
No worries, take your time! And best of look to you!

**Comment by EagleoutIce** [comment]
After #785 this should be much easier again especially because the split is no longer necessary (changes :heart:), adapt whenever you have time!

**Comment by Ellpeck** [comment]
Thanks so much again for all your work on this!! I'll try to take care of getting the merge sorted, and then this should be ready to go! :)

**Comment by Ellpeck** [comment]
closing in favor of #868

**Pull request closed without merging**
