### PR TITLE
[Doc] Improve in-code documentation

### PR DESCRIPTION
**Pull request by EagleoutIce**

### CODE REVIEW

**Review by Ellpeck — APPROVED** [review]
oooh this is very nice!!

**Comment by gigalasr** [comment]
Awesome!

**Review by gigalasr — APPROVED** [review]

**Review by Slartibartfass2 — APPROVED** [review]
Great!

**Comment by EagleoutIce** [comment]
_This pull request is included in v2.1.9 (see [Release v2.1.9 (Improved Closure Slicing, DFG docs, and Support for the Car Package)](https://github.com/flowr-analysis/flowr/releases/tag/v2.1.9))._

**Pull request merged**
