### PR TITLE
[Tests] Basic System Tests

### PR DESCRIPTION
**Pull request by gigalasr**

### CODE REVIEW

**Comment by gigalasr** [comment]
@EagleoutIce How should the system tests be executed in the ci? SHould there be an extra step or should they be executed with test-full (change package.json) ?

**Comment by EagleoutIce** [comment]
> @EagleoutIce Would you like me to add any of the examples you use often that you mentioned? If yes could you provide them?

For now it is fine to test something like `:df x <- 3` and `:df "x <- 3\nprint(x)"`. I can do the rest.

**Comment by EagleoutIce** [comment]
> @EagleoutIce How should the system tests be executed in the ci? SHould there be an extra step or should they be executed with test-full (change package.json) ?

A separate step would be fine to have `test:system` or something like that. This should be not part of `test-full` but part of `checkup`

**Comment by EagleoutIce** [comment]
_This pull request is included in v2.1.9 (see [Release v2.1.9 (Improved Closure Slicing, DFG docs, and Support for the Car Package)](https://github.com/flowr-analysis/flowr/releases/tag/v2.1.9))._

**Pull request merged**
